@startuml
!include Interfaces.puml

interface MutableMap

package adjacencymap {
    abstract class AdjacencyMapGraph<Vertex> {
        - _adjacencyMap : MutableMap<Vertex, MutableSet<Vertex>>

        + containsVertex(vertex: Vertex): Boolean
        + isAdjacent(from: Vertex, to: Vertex): Boolean
        + neighbors(vertex: Vertex): Set<Vertex>?
        + equals(other: Any?): Boolean
        + hashCode(): Int
    }
    AdjacencyMapGraph --> MutableMap
    AdjacencyMapGraph --> Graph

    abstract class MutableAdjacencyMapGraph<Vertex, EdgeValue> {
        + addVertex(vertex: Vertex): Boolean
        + removeVertex(vertex: Vertex): Boolean
        + removeEdge(from: Vertex, to: Vertex): Boolean
        + addEdge(from: Vertex, to: Vertex, value: EdgeValue?): Boolean
    }
    MutableAdjacencyMapGraph --> Graph
    MutableAdjacencyMapGraph --> Mutable
    MutableAdjacencyMapGraph --> AdjacencyMapGraph

    class AdjacencyMapMutableGraphImpl<Vertex> {
        + addEdge(from: Vertex, to: Vertex): Boolean
    }
    AdjacencyMapMutableGraphImpl --> MutableGraph
    AdjacencyMapMutableGraphImpl --> MutableAdjacencyMapGraph

    class ValuedAdjacencyMapMutableGraphImpl<Vertex, EdgeValue> {
        + addEdge(from: Vertex, to: Vertex, value: EdgeValue): Boolean
        + getEdgeValue(from: Vertex, to: Vertex): EdgeValue?
        + putEdgeValue(from: Vertex, to: Vertex, value: EdgeValue)
        + removeEdgeValue(from: Vertex, to: Vertex): Boolean
    }
    ValuedAdjacencyMapMutableGraphImpl --> ValuedGraph
    ValuedAdjacencyMapMutableGraphImpl --> ValuedMutableGraph
    ValuedAdjacencyMapMutableGraphImpl --> MutableAdjacencyMapGraph

}

@enduml